### ISSUE TITLE
Complexes in Alphafold2_batch colab

### ISSUE THREAD

**Issue by jabard89** [sokrypton/ColabFold#138]
## Expected Behavior
I would like to run complexes in the google colab Alphafold2_batch. My understanding is that the proper input is a bunch of fastas with sequence in each fasta where the complex is joined with ":"
## Current Behavior
I get an error when loading the sequences
## Steps to Reproduce (for bugs)
file in input folder is test.fasta
">test
MADITDKTAEQLENLNIQDD:KQAATGSESQSVENSSASLYV"
## ColabFold Output (for bugs)
2022-01-13 22:28:56,705 Running colabfold 1.2.0 (ee8e17402a3ce8aa67669d3ea22958ef99b808d9)
2022-01-13 22:28:56,714 Found 5 citations for tools or databases
2022-01-13 22:29:02,286 Query 1/1: test (length 42)
PENDING:   0%|          | 0/150 [elapsed: 00:00 remaining: ?]2022-01-13 22:29:02,439 Sleeping for 9s. Reason: PENDING
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:09 remaining: 00:00]2022-01-13 22:29:11,666 Could not generate input features test: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 1046, in run
    model_type,
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 757, in generate_input_feature
    sequence, input_msa, template_features[sequence_index]
  File "/usr/local/lib/python3.7/dist-packages/colabfold/batch.py", line 628, in build_monomer_feature
    sequence=sequence, description="none", num_res=len(sequence)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/data/pipeline.py", line 43, in make_sequence_features
    map_unknown_to_x=True)
  File "/usr/local/lib/python3.7/dist-packages/alphafold/common/residue_constants.py", line 580, in sequence_to_onehot
    raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: :
2022-01-13 22:29:11,667 Done

**Comment by eckhard-hofmann** [comment]
Same behaviour here...
Its a great pipeline and supposed to work. We just need the info about the proper format of the .fasta files... ;-)
Thanks for your efforts!!!

**Comment by martin-steinegger** [comment]
This should be fixed now. You can just use `.fasta` files with chains separated by `:`
Alternative, you can our `.csv` format: 

```
id,sequence
ID1,VVV:AAA
ID2,LALA:LLLL
...
```

**Comment by serbulent-av** [comment]
Hi, 

I'm using docker image ghcr.io/sokrypton/colabfold:1.5.3-cuda11.8.0 however still encounter with the same error. I think this update hasn't been committed into this image.

**Comment by milot-mirdita** [comment]
I updated the 1.5.3 docker images a few hours ago to add a bugfix. Please pull the image again. And please make a new issue with the full output and error message.

**Comment by serbulent-av** [comment]
It works now, thank you.

--

Serbülent Ünsal, Ph.D.

Senior ML Engineer


+44 737 647 25 15

+90 555 697 50 46

www.antiverse.io
[image: Future of Drug Discovery Podcast] <https://anchor.fm/fodd>
