### ISSUE TITLE
Could not override field 'num_extra_msa' (reference)

### ISSUE THREAD

**Issue by gezmi** [sokrypton/ColabFold#363]
## Expected Behavior
Running AF2 from the beta branch with AF-2Multimer version 3 

## Current Behavior
Crashing with error

## Steps to Reproduce (for bugs)
input seq: MAGAGGGNDIQWCFSQVKGAVDDDVAEADIISTVEFNHSGELLATGDKGGRVVIFQQEQENKIQSHSRGE YNVYSTFQSHEPEFDYLKSLEIEEKINKIRWLPQKNAAQFLLSTNDKTIKLWKISERDKRPEGYNLKEED GRYRDPTTVTTLRVPVFRPMDLMVEASPRRIFANAHTYHINSISINSDYETYLSADDLRINLWHLEITDR SFNIVDIKPANMEELTEVITAAEFHPNSCNTFVYSSSKGTIRLCDMRASALCDRHSKLFEEPEDPSNRSF FSEIISSISDVKFSHSGRYMMTRDYLSVKIWDLNMENRPVETYQVHEYLRSKLCSLYENDCIFDKFECCW NGSDSVVMTGSYNNFFRMFDRNTKRDITLEASRENNKPRTVLKPRKVCASGKRKKDEISVDSLDFNKKIL HTAWHPKENIIAVATTNNLYIFQDKVN:MSAPSLGRFVPRRFLLPEYLPYAGI
templates change to pd70

## ColabFold Output (for bugs)
![image](https://user-images.githubusercontent.com/13509667/215760622-9c6c3bd7-4f6a-404e-bc77-6d20fd14e6f6.png)

## Your Environment
COLAB

**Comment by sokrypton** [comment]
Thanks! Should be fixed now.

**Comment by gezmi** [comment]
Thank you Sergey! I still cannot cannot  get it to run, now it does not find GPU/TPU
![image](https://user-images.githubusercontent.com/13509667/215780928-d4210f23-247f-41a9-9349-e4b640b76482.png)

The runtime is GPU
![image](https://user-images.githubusercontent.com/13509667/215781038-4e285350-38a2-486a-9e74-7c56ae9b6882.png)

Can you help also with this? My collegaue has the same error.

**Comment by sokrypton** [comment]
Oh, you can ignore that error. It just says it cannot find TPU. GPU is
being used.
