### ISSUE TITLE
Install fails with notebook relax_amber.ipynb

### ISSUE THREAD

**Issue by jfbazan** [sokrypton/ColabFold#440]
On the heels of the recently resolved issue #437––an early fail during the install of dependencies, traced to incompatibility with Amber version used––I've noticed that a ~similar failure occurs during the 'install amber' phase of the (quite useful!) relax_amber.ipynb Colab notebook, after some ~15 min or so of spinning its wheels. Makes sense that the observed Amber issues would also affect this notebook! Anyway, here's the beginning of the very long error msg, followed by the end bit. Thanks again in advance for checking this out!

19%.. 19/100 [elapsed: 17:36 remaining: 00:53]
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting py3dmol
  Downloading py3Dmol-2.0.1.post1-py2.py3-none-any.whl (12 kB)
Installing collected packages: py3dmol
Successfully installed py3dmol-2.0.1.post1
PREFIX=/opt/conda
Unpacking payload ...
                                                                                      
Installing base environment...

Downloading and Extracting Packages

Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /opt/conda
env: PATH=/opt/conda/bin:/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda==4.13.0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.13.0               |  py310h06a4308_0         905 KB
    ruamel_yaml-0.15.100       |  py310h7f8727e_0         490 KB
    yaml-0.2.5                 |       h7b6447c_0          75 KB
    ------------------------------------------------------------
                                           Total:         1.4 MB

The following NEW packages will be INSTALLED:

  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.100-py310h7f8727e_0 
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0 

The following packages will be DOWNGRADED:

  conda                              23.3.1-py310h06a4308_0 --> 4.13.0-py310h06a4308_0 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pip):

  - openmm=7.5.1 -> numpy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.*|3.9.*|3.8.*']
  - openmm=7.5.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
  - pdbfixer -> numpy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.7|>=3.8']
  - pdbfixer -> python[version='>=3.6']
  - pdbfixer -> setuptools
  - python=3.10 -> pip -> setuptools
  - python=3.10 -> pip -> wheel
...
And then the end of the error msg:

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-1-9e75f296f1a1>](https://localhost:8080/#) in <cell line: 11>()
     24         PATH=get_ipython().run_line_magic('env', 'PATH')
     25         get_ipython().run_line_magic('env', 'PATH=/opt/conda/bin:{PATH}')
---> 26         get_ipython().run_line_magic('shell', 'conda install -qy conda==4.13.0              && conda install -qy -c conda-forge                python={python_version}                openmm=7.5.1                pdbfixer')
     27         pbar.update(80)
     28 

2 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'conda install -qy conda==4.13.0              && conda install -qy -c conda-forge                python=3.10                openmm=7.5.1                pdbfixer' returned non-zero exit status 1.

**Comment by milot-mirdita** [comment]
The issue with the amber standalone notebook should already be fixed. Please reload/update the notebook.

**Comment by jfbazan** [comment]
I reloaded the notebook on a different browser, and it still crashes, albeit in the "Install AlphaFold" phase. Here's the whole error msg:

10%...10/100 [elapsed: 00:12 remaining: 00:19]
Cloning into 'alphafold'...
remote: Enumerating objects: 818, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 818 (delta 8), reused 16 (delta 8), pack-reused 793
Receiving objects: 100% (818/818), 16.03 MiB | 19.50 MiB/s, done.
Resolving deltas: 100% (489/489), done.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting absl-py==1.0.0
  Downloading absl_py-1.0.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.7/126.7 kB 3.2 MB/s eta 0:00:00
Collecting biopython==1.79
  Downloading biopython-1.79-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 36.3 MB/s eta 0:00:00
Collecting chex==0.0.7
  Downloading chex-0.0.7-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 6.4 MB/s eta 0:00:00
Collecting dm-haiku==0.0.9
  Downloading dm_haiku-0.0.9-py3-none-any.whl (352 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.1/352.1 kB 31.8 MB/s eta 0:00:00
Collecting dm-tree==0.1.6
  Downloading dm_tree-0.1.6-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 18.9 MB/s eta 0:00:00
Collecting docker==5.0.0
  Downloading docker-5.0.0-py2.py3-none-any.whl (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.0/147.0 kB 17.8 MB/s eta 0:00:00
Collecting immutabledict==2.0.0
  Downloading immutabledict-2.0.0-py3-none-any.whl (4.0 kB)
Collecting jax==0.3.25
  Downloading jax-0.3.25.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 60.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ml-collections==0.1.0
  Downloading ml_collections-0.1.0-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.7/88.7 kB 11.0 MB/s eta 0:00:00
Collecting numpy==1.21.6
  Downloading numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 77.1 MB/s eta 0:00:00
Collecting pandas==1.3.4
  Downloading pandas-1.3.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 15.9 MB/s eta 0:00:00
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement scipy==1.7.0 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1)
ERROR: No matching distribution found for scipy==1.7.0

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-2-5b4d41321013>](https://localhost:8080/#) in <cell line: 3>()
     10         pbar.update(10)
     11         # Install the required versions of all dependencies.
---> 12         get_ipython().run_line_magic('shell', 'pip3 install -r ./alphafold/requirements.txt')
     13         # Run setup.py to install only AlphaFold.
     14         get_ipython().run_line_magic('shell', 'pip3 install --no-dependencies ./alphafold')

2 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

**Comment by sokrypton** [comment]
Please try again. I've rewrote the setup part to match the main notebook.
