### ISSUE TITLE
AlphaFold2_complexes out of memory

### ISSUE THREAD

**Issue by xvazquezc** [sokrypton/ColabFold#8]
Hi there,

I was trying to model a bacterial protein complex based on the suggestions on top of the notebook, i.e. `pair_msa` and `disable_mmseqs2_filter` options on, when it ran out of memory at the `Gather input features, predict structure` step.
The two input proteins were 901 and 351 amino acids.

I thought it could be a good idea to report the error:
```
pairs found: 417
running model_1_ptm

---------------------------------------------------------------------------

UnfilteredStackTrace                      Traceback (most recent call last)

<ipython-input-7-0be664d1f433> in <module>()
     57 }
---> 58 plddts, paes = predict_structure(jobname, feature_dict, Ls=Ls)

13 frames

UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 12341783136 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
    891           for i, x in enumerate(args)
    892           if x is not token and i in kept_var_idx))
--> 893   out_bufs = compiled.execute(input_bufs)
    894   check_special(xla_call_p.name, out_bufs)
    895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]

RuntimeError: Resource exhausted: Out of memory while trying to allocate 12341783136 bytes.
```

**Comment by xvazquezc** [comment]
Similar issue with the `AlphaFold_wJackhmmer` notebook at the `Run AlphaFold` step. Using the jackhammer option, protein size 901 aa, and homooligomer 1 (both with the turbo option activated and without it).

**Comment by sokrypton** [comment]
Can you try create a new cells and paste:`!nvidia-smi`
Let's see how much memory google-colab gave you.

Example:
![image](https://user-images.githubusercontent.com/4187522/126944339-8d43dbbb-7f4e-40fa-9861-51407c3f97ee.png)

**Comment by xvazquezc** [comment]
This is from the `AlphaFold_wJackhmmer`

```
Mon Jul 26 06:44:40 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

In case it might be of any use, these are the few last entries in the `app.log`:

<html><body>


Timestamp | Level | Message
-- | -- | --
Jul 26, 2021, 4:07:39 PM | WARNING | WARNING:root:kernel d3df6602-992a-4e3d-99af-0aa554d461c7 restarted
Jul 26, 2021, 4:07:39 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jul 26, 2021, 4:07:35 PM | WARNING | tcmalloc:  large alloc 4289486848 bytes == 0x564235732000 @  0x7f5fbdf2fb6b  0x7f5fbdf4f379 0x7f5f1e19de97 0x7f5f0d0f16ef 0x7f5f0d18228b  0x7f5f0cfb12e7 0x7f5f0cfb196f 0x7f5f0cfb1b28 0x7f5f1318facd  0x7f5f0d2b5eb4 0x7f5f0d2aa1fe 0x7f5f12772441 0x7f5f1276f133  0x7f5f0d9f1d75 0x7f5fbdd026db 0x7f5fbce3771f
Jul 26, 2021, 4:07:33 PM | WARNING | tcmalloc:  large alloc 4442021888 bytes == 0x56412caf4000 @  0x7f5fbdf2fb6b  0x7f5fbdf4f379 0x7f5f1e19de97 0x7f5f0d0f16ef 0x7f5f0d18228b  0x7f5f0cfb12e7 0x7f5f0cfb196f 0x7f5f0cfb1b28 0x7f5f1318facd  0x7f5f0d2b5eb4 0x7f5f0d2aa1fe 0x7f5f12772441 0x7f5f1276f133  0x7f5f0d9f1d75 0x7f5fbdd026db 0x7f5fbce3771f
Jul 26, 2021, 4:07:22 PM | WARNING | 2021-07-26  06:07:22.142458: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 194976400 exceeds 10% of free system memory.
Jul 26, 2021, 4:07:22 PM | WARNING | 2021-07-26  06:07:22.142392: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 194976400 exceeds 10% of free system memory.
Jul 26, 2021, 4:07:22 PM | WARNING | 2021-07-26  06:07:22.059009: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 194976400 exceeds 10% of free system memory.
Jul 26, 2021, 4:07:21 PM | WARNING | 2021-07-26  06:07:21.914371: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 194976400 exceeds 10% of free system memory.
Jul 26, 2021, 4:07:21 PM | WARNING | 2021-07-26  06:07:21.914309: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 194976400 exceeds 10% of free system memory.
Jul 26, 2021, 4:07:21 PM | WARNING | 2021-07-26  06:07:21.380965: W  tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding  allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment  variable is set. Original config value was 0.


</body>
</html>

**Comment by g-e-kenney** [comment]
For what it's worth, I'm running into a similar issue when looking for homodimers of large-ish (600-700 aa) proteins (with pair-msa off). I get an out of memory error during the construction of the first model.  I've seen this with several, so it's not sequence-specific.  I also get ~the same error (with the same runtime error traceback, even) on the non-complexes server with the homooligomer = 2 option.

```
running model_1_ptm
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-15-0be664d1f433> in <module>()
     57 }
---> 58 plddts, paes = predict_structure(jobname, feature_dict, Ls=Ls)
13 frames
UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 10776336544 bytes.
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
    891           for i, x in enumerate(args)
    892           if x is not token and i in kept_var_idx))
--> 893   out_bufs = compiled.execute(input_bufs)
    894   check_special(xla_call_p.name, out_bufs)
    895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]
RuntimeError: Resource exhausted: Out of memory while trying to allocate 10776336544 bytes.
```

Here's what I get for :!nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    27W /  70W |  14010MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+                                                                          
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by sokrypton** [comment]
The absolute best we can do is 1400 AA on a 16 GB GPU (typically provided by Google-Colab).

@g-e-kenney I've made some updates that should help for the homo-oligomer case. Can you try:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold_wJackhmmer.ipynb

@xvazquezc I'm working on updating the complexes notebook now.

**Comment by sokrypton** [comment]
@xvazquezc can you try again? I've updated the notebook. Hopefully, this decreases memory usage:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2_complexes.ipynb

**Comment by xvazquezc** [comment]
Hi @sokrypton , it's 901 and 351 (heterodimer)

It crashed again. I include the last entries from the `app.log`:

<html><body>


Timestamp | Level | Message
-- | -- | --
Jul 29, 2021, 12:46:42 PM | WARNING | WARNING:root:kernel ab28adda-7a28-4da9-b999-d93dd86e5f40 restarted
Jul 29, 2021, 12:46:42 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jul 29, 2021, 12:46:38 PM | WARNING | tcmalloc:  large alloc 3696648192 bytes == 0x55f7fe51a000 @  0x7feb9c91bb6b  0x7feb9c93b379 0x7feb5718de97 0x7feb460e16ef 0x7feb4617228b  0x7feb45fa12e7 0x7feb45fa196f 0x7feb45fa1b28 0x7feb4c17facd  0x7feb462a5eb4 0x7feb4629a1fe 0x7feb4b762441 0x7feb4b75f133  0x7feb469e1d75 0x7feb9c6ee6db 0x7feb9b82371f
Jul 29, 2021, 12:46:38 PM | WARNING | 2021-07-29  02:46:38.179833: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 3696644952 exceeds 10% of free system memory.
Jul 29, 2021, 12:46:38 PM | WARNING | tcmalloc:  large alloc 3805749248 bytes == 0x55f71b7a8000 @  0x7feb9c91bb6b  0x7feb9c93b379 0x7feb5718de97 0x7feb460e16ef 0x7feb4617228b  0x7feb45fa12e7 0x7feb45fa196f 0x7feb45fa1b28 0x7feb4c17facd  0x7feb462a5eb4 0x7feb4629a1fe 0x7feb4b762441 0x7feb4b75f133  0x7feb469e1d75 0x7feb9c6ee6db 0x7feb9b82371f
Jul 29, 2021, 12:46:38 PM | WARNING | 2021-07-29  02:46:38.169689: W tensorflow/core/framework/cpu_allocator_impl.cc:80]  Allocation of 3805747164 exceeds 10% of free system memory.
Jul 29, 2021, 12:46:29 PM | WARNING | 2021-07-29 02:46:29.039857: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199995000 Hz
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.897010: I  tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created  TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with  13425 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus  id: 0000:00:04.0, compute capability: 7.5)
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.896948: W  tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding  allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment  variable is set. Original config value was 0.
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.896111: I  tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful  NUMA node read from SysFS had negative value (-1), but there must be at  least one NUMA node, so returning NUMA node zero
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.895122: I  tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful  NUMA node read from SysFS had negative value (-1), but there must be at  least one NUMA node, so returning NUMA node zero
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.893608: I  tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful  NUMA node read from SysFS had negative value (-1), but there must be at  least one NUMA node, so returning NUMA node zero
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29 02:46:28.893366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29 02:46:28.893352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
Jul 29, 2021, 12:46:28 PM | WARNING | 2021-07-29  02:46:28.893299: I  tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device  interconnect StreamExecutor with strength 1 edge matrix:


</body>
</html>

**Comment by sokrypton** [comment]
@xvazquezc can you share the sequences (you can email if it's private: so@fas.harvard.edu ) . I can try.

**Comment by xvazquezc** [comment]
ok. will do

**Comment by sokrypton** [comment]
@xvazquezc I think all should be resolved now! Please try again :D

**Comment by g-e-kenney** [comment]
Still getting the same out-of-memory error on the homo-oligomers, for what it's worth, even starting with some of the slightly smaller ones (~570 aa) and running on the Jackhmmer setup.

**Comment by sokrypton** [comment]
@g-e-kenney Thanks for checking!
For a typical Google-Colab session, with a 16G-GPU, the max total length is 1400 residues. Unfortunately, sometimes a 12G-GPU is assigned, in which the max total length is ~1000 residues. I wonder if in your last run you got the 12GB-GPU...

**Comment by xvazquezc** [comment]
@sokrypton , it ran until completion.
Thanks

**Comment by g-e-kenney** [comment]
Still running into memory errors on the 550-650 aa homodimers.  (I haven't had much luck getting GPU sessions of any variety for the past bunch of days, so I haven't really been able to see whether or not this is exacerbated by some of the options on the jackhmmer notebook, e.g. jackhmmer vs. mmseqs2, choosing relax_all or not, and so on.)

**Comment by sokrypton** [comment]
@g-e-kenney I did some optimization to reduce memory. Here is an updated notebook:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb

Can you try again?

**Comment by g-e-kenney** [comment]
I've been able to get one run to complete, so it's definitely an improvement, but I've still had issues (possibly with running out of allotted time and/or resources on a Colab instance - I'm not getting the explicit error above anymore, just a general error notice + disconnection from the instance?)

**Comment by g-e-kenney** [comment]
(I'd be happy to send over some of my problem sequences if that'd help!)

**Comment by sjbandekar** [comment]
> Hi there,
> 
> I was trying to model a bacterial protein complex based on the suggestions on top of the notebook, i.e. `pair_msa` and `disable_mmseqs2_filter` options on, when it ran out of memory at the `Gather input features, predict structure` step.
> The two input proteins were 901 and 351 amino acids.
> 
> I thought it could be a good idea to report the error:
> 
> ```
> pairs found: 417
> running model_1_ptm
> 
> ---------------------------------------------------------------------------
> 
> UnfilteredStackTrace                      Traceback (most recent call last)
> 
> <ipython-input-7-0be664d1f433> in <module>()
>      57 }
> ---> 58 plddts, paes = predict_structure(jobname, feature_dict, Ls=Ls)
> 
> 13 frames
> 
> UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 12341783136 bytes.
> 
> The stack trace below excludes JAX-internal frames.
> The preceding is the original exception that occurred, unmodified.
> 
> --------------------
> 
> 
> The above exception was the direct cause of the following exception:
> 
> RuntimeError                              Traceback (most recent call last)
> 
> /usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
>     891           for i, x in enumerate(args)
>     892           if x is not token and i in kept_var_idx))
> --> 893   out_bufs = compiled.execute(input_bufs)
>     894   check_special(xla_call_p.name, out_bufs)
>     895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]
> 
> RuntimeError: Resource exhausted: Out of memory while trying to allocate 12341783136 bytes.
> ```

Hi @sokrypton! 

I am having a similar issue when trying to predict a monomeric protein of ~1500 residues. Even when I trim it down to sequences ~ 1200 residues, I still get the RAM error. I was wondering if there was possible to implement a cap for residue length based on the amount of VRAM you are assigned using google colab.

Thanks for your hard work implementing this, it has helped my build portions of my structure already!

**Comment by sokrypton** [comment]
Hi @sjbandekar 
Can you try using our new advanced notebook, which now has support for complexes:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb

There were a few improvements related to memory usage.
